"""MIRIAM-style RDF annotation shared by the CellML and SBML builders.

Every exported model carries:
  - ``harmonia:clinicalUse = "PROHIBITED ..."`` — universal, machine-readable;
  - ``harmonia:confidenceTier`` — the propagated tier;
  - ``harmonia:datasetVersion`` — the dataset version pin;
  - ``bqbiol:isDescribedBy`` links to the primary-source DOIs (these survive
    predicate-stripping because the DOI is the rdf:resource).
"""
from __future__ import annotations

from typing import Iterable, List, Optional

CLINICAL_USE = ("PROHIBITED — research / safety-methodology / education only; "
                "not a regulatory determination")

HARMONIA_NS = "https://github.com/clay-good/harmonia/ns#"
BQBIOL = "http://biomodels.net/biology-qualifiers/"
DCTERMS = "http://purl.org/dc/terms/"


def doi_uri(doi: str) -> str:
    return f"https://doi.org/{doi}"


def rdf_block(meta_id: str, tier: str, dataset_version: str,
              dois: Iterable[str] = (), indent: str = "  ") -> str:
    """An RDF/XML annotation block for a model with metaid ``meta_id``."""
    described = "".join(
        f'\n{indent}      <bqbiol:isDescribedBy rdf:resource="{doi_uri(d)}"/>'
        for d in dois if d)
    return (
        f'{indent}<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"\n'
        f'{indent}         xmlns:bqbiol="{BQBIOL}"\n'
        f'{indent}         xmlns:dcterms="{DCTERMS}"\n'
        f'{indent}         xmlns:harmonia="{HARMONIA_NS}">\n'
        f'{indent}  <rdf:Description rdf:about="#{meta_id}">\n'
        f'{indent}    <harmonia:clinicalUse>{CLINICAL_USE}</harmonia:clinicalUse>\n'
        f'{indent}    <harmonia:confidenceTier>{tier}</harmonia:confidenceTier>\n'
        f'{indent}    <harmonia:datasetVersion>{dataset_version}</harmonia:datasetVersion>'
        f'{described}\n'
        f'{indent}  </rdf:Description>\n'
        f'{indent}</rdf:RDF>\n'
    )


def provenance_comment(dois: Optional[List[str]] = None) -> str:
    lines = [
        "Generated by Harmonia — DO NOT HAND-EDIT (regenerated from dataset/ in CI).",
        CLINICAL_USE,
        "This model is a REDUCED reference kernel of the O'Hara-Rudy lineage; it is",
        "research / education infrastructure, not a regulatory or clinical tool.",
    ]
    if dois:
        lines.append("Primary sources: " + ", ".join(doi_uri(d) for d in dois))
    return "\n".join(lines)
